FROM node:22-bookworm-slim

# Install Chrome dependencies
RUN apt-get update
RUN apt install -y \
  libnss3 \
  libdbus-1-3 \
  libatk1.0-0 \
  libgbm-dev \
  libasound2 \
  libxrandr2 \
  libxkbcommon-dev \
  libxfixes3 \
  libxcomposite1 \
  libxdamage1 \
  libatk-bridge2.0-0 \
  libpango-1.0-0 \
  libcairo2 \
  libcups2

WORKDIR /app

# 安装nodemon用于热重载
RUN npm install -g nodemon @alicloud/fun

COPY package*.json ./

RUN npm install

COPY . .

# 开发环境不需要构建
CMD ["npm", "run", "dev"]