version: '3.8'
services:
  renderer:
    build: 
      context: .
      dockerfile: Dockerfile.dev  # 我们将创建一个专门用于开发的Dockerfile
    container_name: remotion-renderer-dev
    volumes:
      - .:/app  # 将当前目录挂载到容器的/app目录
      - /app/node_modules  # 防止本地node_modules覆盖容器内的
    ports:
      - "3000:3000"  # 暴露服务端口
    environment:
      - NODE_ENV=development
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - ACCESS_KEY_SECRET=${ACCESS_KEY_SECRET}
      - OSS_REGION=${OSS_REGION}
      - OSS_BUCKET=${OSS_BUCKET}
    command: npm run dev  # 我们将添加一个dev script到package.json